trigger: none
pr: none

resources:
  pipelines:
    - pipeline: ciPipeline
      source: CI
      trigger:
        branches:
          include:
            - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Azure for Students(07de936b-e0c8-47b8-b15f-3d778712ecb6)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az container create -g $(resourceGroup) \
        --name $(appName) \
        --image acr129.azurecr.io/fcg129:33 \
        --cpu 1 \
        --memory 1 \
        --location eastus \
        --os-type Linux \
        --registry-login-server acr129.azurecr.io \
        --registry-username acr129 \
        --registry-password $(acrPassword) \
        --ports 80