trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Deploy
    displayName: "Deploy da aplicação"
    jobs:
      - job: DeployApplication
        displayName: "Escrever mensagem de deploy"
        steps:
          - script: echo "Deploy da aplicação iniciado"
