trigger: none
pr: none

resources:
  pipelines:
    - pipeline: ciPipeline
      source: CI
      trigger:
        branches:
          include:
            - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureContainerApps@1
  inputs:
    appSourcePath: '.'
    azureSubscription: 'Azure for Students($(subscription))'
    acrName: '$(acrName)'
    acrUsername: '$(acrUsername)'
    location: 'northeurope'
    acrPassword: '$(acrPassword)'
    imageToDeploy: '$(acrLoginServer)/$(acrName):$(resources.pipeline.ciPipeline.runID)'
    containerAppName: '$(appName)'
    resourceGroup: '$(resourceGroup)'
    targetPort: '8080'
  displayName: 'Construir e Rodar o Contêiner Docker com a Aplicação .NET'

- script: |
    docker run \
    -d \
    --name newrelic-infra \
    --network=host \
    --cap-add=SYS_PTRACE \
    --privileged \
    --pid=host \
    -v "/:/host:ro" \
    -v "/var/run/docker.sock:/var/run/docker.sock" \
    -e NEW_RELIC_LICENSE_KEY='$(nrKey)' \
    newrelic/infrastructure:latest
  displayName: 'Construir e Rodar o Contêiner Docker com New Relic'