trigger: none
pr: none

resources:
  pipelines:
    - pipeline: ciPipeline
      source: CI
      trigger:
        branches:
          include:
            - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      artifactName: 'drop'
      targetPath: '$(Pipeline.Workspace)/drop'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Azure for Students(07de936b-e0c8-47b8-b15f-3d778712ecb6)'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az container create -g $(resourceGroup)
        --name $(appName)
        --image $(acrLoginServer)/$(acrName):latest 
        --cpu 1
        --memory 1
        --registry-login-server $(acrLoginServer)
        --registry-username $(acrName)
        --registry-password $(acrPassword)
        --ports 80